#!/usr/bin/env bash
# displays Best  School 10 times but for the 9th, displays Best School and then Hi on a new line

COUNT=0
while [ "$COUNT" -lt 10 ];
do
	echo "Best School"
	if [ "$COUNT" -eq 8 ]
	then
	    echo "Hi"
	fi
	let COUNT=COUNT+1
done
